const articles = [
  {
    id: 0,
    title: "Article 1",
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. ",
    author: "John Doe",
    creationDate: "21 Jan 2019",
    readMinuteTime: 5,
  },
  {
    id: 1,
    title: "Article 2",
    body: "Amet risus nullam eget felis eget nunc lobortis. Euismod quis viverra nibh cras pulvinar mattis nunc sed blandit. Enim praesent elementum facilisis leo vel fringilla est. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque. Diam vel quam elementum pulvinar etiam non quam lacus suspendisse. Risus sed vulputate odio ut enim blandit. Eu facilisis sed odio morbi quis commodo odio. Fermentum iaculis eu non diam phasellus. Sit amet nisl suscipit adipiscing bibendum. Fringilla est ullamcorper eget nulla facilisi etiam dignissim diam.",
    author: "John Doe",
    creationDate: "23 Jan 2019",
    readMinuteTime: 7,
  },
  {
    id: 2,
    title: "Article 3",
    body: "Nisi quis eleifend quam adipiscing vitae. Mauris in aliquam sem fringilla ut. Elementum eu facilisis sed odio morbi. Morbi non arcu risus quis varius quam. Nulla facilisi etiam dignissim diam quis. Nam aliquam sem et tortor consequat. Lacus laoreet non curabitur gravida arcu. Consequat nisl vel pretium lectus quam. Duis at consectetur lorem donec massa sapien. Ultrices gravida dictum fusce ut. Nunc id cursus metus aliquam eleifend mi in nulla posuere. Lacus suspendisse faucibus interdum posuere lorem ipsum dolor. Ultrices gravida dictum fusce ut placerat orci nulla. Ultrices mi tempus imperdiet nulla malesuada. Consectetur adipiscing elit pellentesque habitant morbi tristique. Quam vulputate dignissim suspendisse in est ante in nibh. Pulvinar sapien et ligula ullamcorper malesuada proin libero nunc consequat. Venenatis urna cursus eget nunc scelerisque viverra mauris.",
    author: "John Doe",
    creationDate: "25 Jan 2019",
    readMinuteTime: 4,
  },
  {
    id: 3,
    title: "Article 4",
    body: "Non sodales neque sodales ut etiam. Ullamcorper malesuada proin libero nunc consequat. Volutpat blandit aliquam etiam erat velit scelerisque in dictum. Odio tempor orci dapibus ultrices. Eget mi proin sed libero enim. Urna et pharetra pharetra massa. At urna condimentum mattis pellentesque id. Ut sem viverra aliquet eget. Quis vel eros donec ac odio tempor orci. Venenatis tellus in metus vulputate eu scelerisque. Luctus accumsan tortor posuere ac ut consequat semper viverra nam. Fames ac turpis egestas maecenas pharetra convallis posuere morbi.",
    author: "John Doe",
    creationDate: "28 Jan 2019",
    readMinuteTime: 3,
  },
  {
    id: 4,
    title: "Article 5",
    body: "Non sodales neque sodales ut etiam. Ullamcorper malesuada proin libero nunc consequat. Volutpat blandit aliquam etiam erat velit scelerisque in dictum. Odio tempor orci dapibus ultrices. Eget mi proin sed libero enim. Urna et pharetra pharetra massa. At urna condimentum mattis pellentesque id. Ut sem viverra aliquet eget. Quis vel eros donec ac odio tempor orci. Venenatis tellus in metus vulputate eu scelerisque. Luctus accumsan tortor posuere ac ut consequat semper viverra nam. Fames ac turpis egestas maecenas pharetra convallis posuere morbi.",
    author: "John Doe",
    creationDate: "28 Jan 2019",
    readMinuteTime: 12,
  },
  {
    id: 5,
    title: "Article 6",
    body: "Non sodales neque sodales ut etiam. Ullamcorper malesuada proin libero nunc consequat. Volutpat blandit aliquam etiam erat velit scelerisque in dictum. Odio tempor orci dapibus ultrices. Eget mi proin sed libero enim. Urna et pharetra pharetra massa. At urna condimentum mattis pellentesque id. Ut sem viverra aliquet eget. Quis vel eros donec ac odio tempor orci. Venenatis tellus in metus vulputate eu scelerisque. Luctus accumsan tortor posuere ac ut consequat semper viverra nam. Fames ac turpis egestas maecenas pharetra convallis posuere morbi.",
    author: "John Doe",
    creationDate: "28 Jan 2019",
    readMinuteTime: 18,
  },
  {
    id: 6,
    title: "Article 7",
    body: "Non sodales neque sodales ut etiam. Ullamcorper malesuada proin libero nunc consequat. Volutpat blandit aliquam etiam erat velit scelerisque in dictum. Odio tempor orci dapibus ultrices. Eget mi proin sed libero enim. Urna et pharetra pharetra massa. At urna condimentum mattis pellentesque id. Ut sem viverra aliquet eget. Quis vel eros donec ac odio tempor orci. Venenatis tellus in metus vulputate eu scelerisque. Luctus accumsan tortor posuere ac ut consequat semper viverra nam. Fames ac turpis egestas maecenas pharetra convallis posuere morbi.",
    author: "John Doe",
    creationDate: "28 Jan 2019",
    readMinuteTime: 5,
  },
  {
    id: 5,
    title: "Article 8",
    body: "Non sodales neque sodales ut etiam. Ullamcorper malesuada proin libero nunc consequat. Volutpat blandit aliquam etiam erat velit scelerisque in dictum. Odio tempor orci dapibus ultrices. Eget mi proin sed libero enim. Urna et pharetra pharetra massa. At urna condimentum mattis pellentesque id. Ut sem viverra aliquet eget. Quis vel eros donec ac odio tempor orci. Venenatis tellus in metus vulputate eu scelerisque. Luctus accumsan tortor posuere ac ut consequat semper viverra nam. Fames ac turpis egestas maecenas pharetra convallis posuere morbi.",
    author: "John Doe",
    creationDate: "28 Jan 2019",
    readMinuteTime: 8,
  },
];

export default articles;
